sudo: required
services:
  - docker

before_install:
  - docker build -t udeshyagiri/docker-react-dummy -f Dockerfile.dev .

script:
  - docker run -e CI=true udeshyagiri/docker-react-dummy npm run test
